security:
    role_hierarchy:
        ROLE_EDITOR: ROLE_USER
        ROLE_ADMIN: ROLE_EDITOR
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        users_in_memory:
            memory:
                users:
                    user:
                        password: '$2y$12$lOXa59njFTdS5kE4aHfgCOg4vMbKP9uRH.DwZMFxzdTimZ/7h2UyK'   # user
                        roles: 'ROLE_USER'
                    editor:
                        password: '$2y$12$/tob0f80d.oRcHJFg4VFG.0QPE8igzjXFVhhe0NSciJSwvIkyzQB.'   # editor
                        roles: 'ROLE_EDITOR'
                    admin:
                        password: '$2y$12$1srZkLLJcbWfYOPN4uaF8eeH61WB05fr7YDHcA/hxVFIX7pvYXY1a'   # admin
                        roles: 'ROLE_ADMIN'
                    superadmin:
                        password: '$2y$12$/tTJsCOtLkxX8g6UvJFkROpoW8FkLj69TBw1RcotlF6tddLApyIfu'   # superadmin
                        roles: 'ROLE_SUPER_ADMIN'

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: users_in_memory
            form_login:
                login_path: login
                check_path: login
                csrf_token_id: authenticate
                default_target_path: /
                enable_csrf: true
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/index, roles: ROLE_EDITOR }
        - { path: ^/index, roles: ROLE_USER }

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
